-- HIPWORD DDL

-- DROP TABLE IF EXISTS TB_HIPWORD_SONG_KEY;
-- DROP TABLE IF EXISTS TB_HIPWORD_ARTIST_KEY;
-- DROP TABLE IF EXISTS TB_HIPWORD_ALBUM_KEY;
DROP TABLE IF EXISTS TB_HIPWORD_RANK;
DROP TABLE IF EXISTS TB_HIPWORD_SONG;
DROP TABLE IF EXISTS TB_HIPWORD_ARTIST;
-- DROP TABLE IF EXISTS TB_HIPWORD_ALBUM;


-- ######################################################################################################################
-- 														   TABLE 
-- ######################################################################################################################


-- SONG 
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_SONG` (
	`SONG_ID` VARCHAR(10) NOT NULL,
	`SONG_TITLE` VARCHAR(100),
	`ARTIST_ID` VARCHAR(10) NOT NULL,
	`LYRICS` VARCHAR(4000),
	PRIMARY KEY(`SONG_ID`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_GENERAL_CI;


-- ARTIST
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_ARTIST` (
	`ARTIST_ID` VARCHAR(10) NOT NULL,
	`ARTIST_NAME` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`ARTIST_ID`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_GENERAL_CI;


-- RANK
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_RANK` (
	`RANK_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`SONG_ID` VARCHAR(10) NOT NULL,
	`SONG_RANK` INT NOT NULL,
	`REG_DATE` DATE NOT NULL DEFAULT NOW(),
	PRIMARY KEY(`RANK_NO`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_GENERAL_CI;


-- ######################################################################################################################
-- 														CONSTRAINT 
-- ######################################################################################################################

ALTER TABLE `TB_HIPWORD_SONG` ADD CONSTRAINT `FK_HIPWORD_SONG_ARTIST` FOREIGN KEY(`ARTIST_ID`) REFERENCES TB_HIPWORD_ARTIST(`ARTIST_ID`);
ALTER TABLE `TB_HIPWORD_RANK` ADD CONSTRAINT `FK_HIPWORD_SONG_RANK` FOREIGN KEY(`SONG_ID`) REFERENCES TB_HIPWORD_SONG(`SONG_ID`) ON DELETE CASCADE;

