-- HIPWORD DDL

DROP TABLE IF EXISTS TB_HIPWORD_SONG_KEY;
DROP TABLE IF EXISTS TB_HIPWORD_ARTIST_KEY;
DROP TABLE IF EXISTS TB_HIPWORD_ALBUM_KEY;
DROP TABLE IF EXISTS TB_HIPWORD_SONG;
DROP TABLE IF EXISTS TB_HIPWORD_ARTIST;
DROP TABLE IF EXISTS TB_HIPWORD_ALBUM;


-- ######################################################################################################################
-- 														   TABLE 
-- ######################################################################################################################


-- SONG 
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_SONG` (
	`SONG_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`SONG_TITLE` VARCHAR(100),
	`ARTIST_NO` INT(11) NOT NULL,
	`ALBUM_NO` INT(11),
	`LYRICS` VARCHAR(2000),
	PRIMARY KEY(`SONG_NO`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_GENERAL_CI;


-- ARTIST
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_ARTIST` (
	`ARTIST_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`ARTIST_NAME` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`ARTIST_NO`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


-- ALBUM
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_ALBUM` (
	`ALBUM_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`ALBUM_NAME` VARCHAR(100) NOT NULL,
	`REG_DATE` DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY(`ALBUM_NO`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


-- SONG KEY
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_SONG_KEY` (
	`SONG_NO` INT(11) NOT NULL,
	`KEY_TYPE` VARCHAR(10) NOT NULL,
	`SONG_ID` VARCHAR(10) NOT NULL,
	PRIMARY KEY(`SONG_NO`, `KEY_TYPE`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


-- ARTIST KEY
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_ARTIST_KEY` (
	`ARTIST_NO` INT(11) NOT NULL,
	`KEY_TYPE` VARCHAR(10) NOT NULL,
	`ARTIST_ID` VARCHAR(10) NOT NULL,
	`ARTIST_ALIAS` VARCHAR(200),
	PRIMARY KEY(`ARTIST_NO`, `KEY_TYPE`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;


-- ALBUM KEY
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_ALBUM_KEY` (
	`ALBUM_NO` INT(11) NOT NULL,
	`KEY_TYPE` VARCHAR(10) NOT NULL,
	`ALBUM_ID` VARCHAR(10) NOT NULL,
	PRIMARY KEY(`ALBUM_NO`, `KEY_TYPE`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COLLATE UTF8_GENERAL_CI;



-- ######################################################################################################################
-- 														CONSTRAINT 
-- ######################################################################################################################

ALTER TABLE `TB_HIPWORD_SONG` ADD CONSTRAINT `FK_HIPWORD_SONG_ARTIST` FOREIGN KEY(`ARTIST_NO`) REFERENCES TB_HIPWORD_ARTIST(`ARTIST_NO`);
ALTER TABLE `TB_HIPWORD_SONG` ADD CONSTRAINT `FK_HIPWORD_SONG_ALBUM` FOREIGN KEY(`ALBUM_NO`) REFERENCES TB_HIPWORD_ALBUM(`ALBUM_NO`) ON DELETE SET NULL;

ALTER TABLE `TB_HIPWORD_SONG_KEY` ADD CONSTRAINT `FK_HIPWORD_SONG_KEY` FOREIGN KEY(`SONG_NO`) REFERENCES TB_HIPWORD_SONG(`SONG_NO`) ON DELETE CASCADE;
ALTER TABLE `TB_HIPWORD_ARTIST_KEY` ADD CONSTRAINT `FK_HIPWORD_ARTIST_KEY` FOREIGN KEY(`ARTIST_NO`) REFERENCES TB_HIPWORD_ARTIST(`ARTIST_NO`) ON DELETE CASCADE;
ALTER TABLE `TB_HIPWORD_ALBUM_KEY` ADD CONSTRAINT `FK_HIPWORD_ALBUM_KEY` FOREIGN KEY(`ALBUM_NO`) REFERENCES TB_HIPWORD_ALBUM(`ALBUM_NO`) ON DELETE CASCADE;



