-- HIPWORD DDL

DROP TABLE IF EXISTS TB_HIPWORD_RANK;
DROP TABLE IF EXISTS TB_HIPWORD_ARTIST;
DROP TABLE IF EXISTS TB_HIPWORD_SONG;

-- ######################################################################################################################
-- 														   TABLE 
-- ######################################################################################################################


-- SONG 
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_SONG` (
	`SONG_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`SONG_ID` VARCHAR(10) NOT NULL UNIQUE,
	`SONG_TITLE` VARCHAR(100) NOT NULL,
	`ARTIST_NO` INT(11) NOT NULL,
	`LYRICS` VARCHAR(4000) NOT NULL,
	PRIMARY KEY(`SONG_NO`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_GENERAL_CI;


-- ARTIST
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_ARTIST` (
	`ARTIST_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`ARTIST_ID` VARCHAR(10) NOT NULL UNIQUE,
	`ARTIST_NAME` VARCHAR(100) NOT NULL,
	PRIMARY KEY(`ARTIST_NO`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_GENERAL_CI;


-- RANK
CREATE TABLE IF NOT EXISTS `TB_HIPWORD_RANK` (
	`RANK_NO` INT(11) NOT NULL AUTO_INCREMENT,
	`SONG_NO` INT(11) NOT NULL,
	`SONG_RANK` INT NOT NULL,
	`REG_DATE` DATE NOT NULL DEFAULT NOW(),
	PRIMARY KEY(`RANK_NO`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8 COLLATE UTF8_GENERAL_CI;


-- ######################################################################################################################
-- 														CONSTRAINT 
-- ######################################################################################################################

ALTER TABLE `TB_HIPWORD_SONG` ADD CONSTRAINT `FK_HIPWORD_SONG_ARTIST` FOREIGN KEY(`ARTIST_NO`) REFERENCES TB_HIPWORD_ARTIST(`ARTIST_NO`);
ALTER TABLE `TB_HIPWORD_RANK` ADD CONSTRAINT `FK_HIPWORD_SONG_RANK` FOREIGN KEY(`SONG_NO`) REFERENCES TB_HIPWORD_SONG(`SONG_NO`) ON DELETE CASCADE;

